export const SERVER_START = 'SERVER_START';
export const SERVER_STOP = 'SERVER_STOP';
export const EXPECTATION_LOAD = 'EXPECTATION_LOAD';
export const EXPECTATION_UNLOAD = 'EXPECTATION_UNLOAD';
export const EXPECTATION_ADD = 'EXPECTATION_ADD';
export const ADD_SERVER = 'ADD_SERVER';
